# Generated by Django 5.2.5 on 2025-08-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("job_level", models.CharField(max_length=50)),
                ("employment_type", models.CharField(max_length=50)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("company_website", models.URLField(blank=True, null=True)),
                ("job_description", models.TextField()),
                ("key_skills", models.TextField()),
                ("education_requirements", models.CharField(max_length=255)),
                (
                    "certifications",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remote_onsite_hybrid", models.CharField(max_length=50)),
                ("skills_match_focus", models.BooleanField(default=False)),
                ("experience_fit_focus", models.BooleanField(default=False)),
                ("education_focus", models.BooleanField(default=False)),
                ("projects_focus", models.BooleanField(default=False)),
                ("ats_keywords_focus", models.BooleanField(default=False)),
                ("additional_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
