# Generated by Django 5.2.5 on 2025-08-21 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_text", models.TextField()),
                ("ats_score", models.IntegerField()),
                ("skill_match_score", models.IntegerField()),
                ("experience_score", models.IntegerField()),
                ("education_score", models.IntegerField()),
                ("overall_score", models.IntegerField()),
                ("feedback", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="api.jobdescription",
                    ),
                ),
            ],
        ),
    ]
